### PR TITLE
Fixing running Ecto 1.x with Erlang r19

### LINKED ISSUE #145: Problems with compiling when using with Elixir 1.3
When you try to do "use ExMachina.Ecto" with Elixir 1.3 I get a compilation error:

```
** (ArgumentError) argument error
    (stdlib) erl_anno.erl:318: :erl_anno.set(:file, 'nofile', -1)
    (stdlib) erl_parse.yrl:1516: anonymous fn/3 in :erl_parse.map_anno/2
    (stdlib) erl_parse.yrl:1631: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1517: :erl_parse.map_anno/2
    (stdlib) erl_lint.erl:703: :erl_lint."-set_file/2-lc$^0/1-0-"/2
    (stdlib) erl_lint.erl:448: :erl_lint.exprs_opt/3
    (stdlib) erl_eval.erl:173: :erl_eval.check_command/2
```

### PR DESCRIPTION
**Pull request by geofflane**
Change the quoting of the macro so it works with Erlang r19 and Elixir 1.3

Should fix #145

### CODE REVIEW

**Comment by paulcsmith** [comment]
Looks like there are some issues on CI. I'll have to take a look later to figure out what's up

**Comment by geofflane** [comment]
@paulcsmith Looks like it's using an old version of Elixir: `sudo apt get install elixir=1.0.5-2`

**Comment by paulcsmith** [comment]
@geofflane Awesome! Would you mind changing that line in your branch's `circle.yml` to `sudo apt-get install elixir` without a version. Then it should re-run with the latest version of elixir

**Comment by geofflane** [comment]
Has warnings, tests pass...

**Comment by paulcsmith** [comment]
There were some warnings, but the tests pass so I think this is good to release since it's a pretty important for people that can't upgrade to ExMachina 1.0 and Ecto 2.0

Thanks for the help @geofflane

**Comment by geofflane** [comment]
Thanks, accidentally closed instead of commented. :)

**Comment by paulcsmith** [comment]
Oops :) Good news is it's now published so you should be good to go now. Thanks for the help
