### ISSUE TITLE
Problems with compiling when using with Elixir 1.3

### ISSUE THREAD

**Issue by wende** [thoughtbot/ex_machina#145]
When you try to do "use ExMachina.Ecto" with Elixir 1.3 I get a compilation error:

```
** (ArgumentError) argument error
    (stdlib) erl_anno.erl:318: :erl_anno.set(:file, 'nofile', -1)
    (stdlib) erl_parse.yrl:1516: anonymous fn/3 in :erl_parse.map_anno/2
    (stdlib) erl_parse.yrl:1631: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1517: :erl_parse.map_anno/2
    (stdlib) erl_lint.erl:703: :erl_lint."-set_file/2-lc$^0/1-0-"/2
    (stdlib) erl_lint.erl:448: :erl_lint.exprs_opt/3
    (stdlib) erl_eval.erl:173: :erl_eval.check_command/2
```

**Comment by paulcsmith** [comment]
Be sure to upgrade ExMachina to 1.0.2

Previous versions do not work with elixir 1.3

Let me know if that does the trick!

**Comment by carakan** [comment]
Same error (erlang19, elixir 1.3), I updated to 1.0.2 but now requires to upgrade ecto to 2.0, any chance to upgrade this without touching ecto? upgrade ecto from 1.x to 2.0 has a lot of breaking changes.

**Comment by paulcsmith** [comment]
@carakan That is a good idea. I've been a bit busy making up for time lost on July 4th. Here is the commit that fixes the issue. I recommend forking from an older version of ExMachina and then applying that commit https://github.com/thoughtbot/ex_machina/commit/4c1158d9bb598d2c7d76902bda70279897dd4aa0

I can make a separate branch for 0.6.x that includes this commit and push to hex for those that can't/don't want to upgrade to ExMachina 1.0/Ecto 2.0 quite yet, but it might be a few days/weeks

**Comment by merqlove** [comment]
👍 Thanks, I will do it now for 0.5 :)

**Comment by merqlove** [comment]
Now i have:
warning: this clause cannot match because a previous clause at line 2 always matches
  lib/in_fact_api/factory.ex:1

It is another one?

**Comment by oliverbarnes** [comment]
Reached the same point, got the same error.

**Comment by geofflane** [comment]
@paulcsmith Wondering if you could push a 0.6.2 with this fix? I just tried it on my own form and it did work with Elixir 1.3 and Erlang r19.

**Comment by paulcsmith** [comment]
@geofflane I've been really busy lately so haven't had much time to work on older version of ExMachina. If you (or someone else) created a PR that works with Erlang r19 and 0.6.2 of ExMachina then I can check it out and publish 0.6.3 to hex.

If not it might be a couple weeks!

**Comment by geofflane** [comment]
@paulcsmith I've got a branch at https://github.com/geofflane/ex_machina/tree/fix_13_build, I don't know how to submit a PR to a tag though? I think I need a branch to submit it.

**Comment by paulcsmith** [comment]
@geofflane Thanks for the help! I've pushed a branch at `ps-0.6.2`. Once the PR is merged I'll tag it and publish to hex!

**Comment by paulcsmith** [comment]
Thanks to @geofflane this should work now. Update to 0.6.2 and you should be good to go!

https://hex.pm/packages/ex_machina/0.6.2
